### ISSUE TITLE
Could you add a license file to this project?

### ISSUE THREAD

**Issue by laike9m** [otiai10/mint#16]
If it's not too much trouble.

**Comment by otiai10** [comment]
Thanks. will you mind I would change it to MIT?

**Comment by laike9m** [comment]
MIT is ok. Thanks 😄

**Comment by laike9m** [comment]
Sorry to bother, but WTFPL is somehow not suited for my usage. Could you use MIT instead?

**Comment by otiai10** [comment]
? I did. I replaced it to MIT.

**Comment by otiai10** [comment]
https://github.com/otiai10/mint/commit/fd1aaf1146c58772d4e047a5564c5771984c1914
